name: Build, Test and Deploy React Application - Production

on:
  push:
    branches: [main]

jobs:
  build_test_prod:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          cd react_test_app
          npm ci

      - name: Generate documentation
        run: |
          cd react_test_app
          npm run jsdoc

      - name: Inject env vars into .env.production
        run: |
          echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" > react_test_app/.env.production

      - name: Run tests
        run: |
          cd react_test_app
          npm test

      - name: Build React app
        run: |
          cd react_test_app
          npm run build
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL_PROD }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./react_test_app/coverage/clover.xml

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: react_test_app/build

      - name: Authenticate with npm
        run: echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" > ~/.npmrc

      - name: Check version and publish if new
        run: |
          cd react_test_app
          LOCAL_VERSION=$(node -p "require('./package.json').version")
          NPM_VERSION=$(npm show @mahautw/react_test_app version || echo "0.0.0")
          if [ "$LOCAL_VERSION" != "$NPM_VERSION" ]; then
            echo "NEW_VERSION=true" >> $GITHUB_ENV
          else
            echo "NEW_VERSION=false" >> $GITHUB_ENV
          fi

      - name: Publish to NPM
        if: env.NEW_VERSION == 'true'
        run: |
          cd react_test_app
          git config --global user.email "mwindal@hotmail.com"
          git config --global user.name "Mahaut Windal"
          npm run build-npm
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  deploy_prod:
    needs: build_test_prod
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://mahautw.github.io/react_test_app/
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v4
